// i18n
import "@/locales/i18n";

import type { Metadata } from "next";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import ThemeProvider from "@/theme";
import { LocalizationProvider } from "@/locales";
import { SettingsDrawer, SettingsProvider } from "@/components/settings";
import { MotionLazy } from "@/components/animate/motion-lazy";
import { SnackbarProvider } from "@/components/snackbar";
import ProgressBar from "@/components/progress-bar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
	return (
		<html lang="en">
			<body>
				<LocalizationProvider>
					<SettingsProvider
						defaultSettings={{
							themeMode: "dark", // 'light' | 'dark'
							themeDirection: "ltr", //  'rtl' | 'ltr'
							themeContrast: "default", // 'default' | 'bold'
							themeLayout: "vertical", // 'vertical' | 'horizontal' | 'mini'
							themeColorPresets: "default", // 'default' | 'cyan' | 'purple' | 'blue' | 'orange' | 'red'
							themeStretch: false,
						}}
					>
						<ThemeProvider>
							<MotionLazy>
								<SnackbarProvider>
									<SettingsDrawer />
									<ProgressBar />
									{children}
									<Analytics />
								</SnackbarProvider>
							</MotionLazy>
						</ThemeProvider>
					</SettingsProvider>
				</LocalizationProvider>
			</body>
		</html>
	);
};

export default RootLayout;
