export const businesses = [
	{
		_id: "67323b77df16afe4bbec8fb3",
		name: "Bookshop 4",
		description: "This a wholesale distributor",
		phone: "254700000003",
		email: "user@email.com",
		category: "hotel and restaurants",
		niche: "long stay",
		sponsored: false,
		isVerified: false,
		priceRange: "1000 - 5000",
		logo: "https://res.cloudinary.com/dqweh6zte/image/upload/v1668515292/starter/tcbh5s9bgx2pnby906nz.jpg",
		location: {
			coordinates: [-1.399046, 33.809838],
			city: "Nairobi",
			country: "Kenya",
		},
		socialMedia: [
			{ name: "facebook", link: "https://www.facebook.com/" },
			{ name: "instagram", link: "https://www.instagram.com/" },
			{ name: "linkedin", link: "https://www.linkedin.com/" },
			{ name: "twitter", link: "https://twitter.com/" },
		],
		owner: "672d16ce0e75dfb18f67baa5",
		photos: [
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704752520/afrex/About/pexels-antony-trivet-14167593_mkakgh.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751922/afrex/About/two-african-businessman-meeting-together_siqvfe.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751125/afrex/homepage/person-office-during-work-day_xgnul0.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704749161/afrex/homepage/complex-aerial-view-city_qsayli.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704895216/afrex/news/blogimage1_zmgpta.png",
		],
	},
	{
		_id: "b246d88c34bdf56fe73d2b44",
		name: "TechHub Innovations",
		description:
			"TechHub Innovations is a tech consulting firm specializing in providing businesses with cutting-edge solutions for digital transformation. We work closely with our clients to identify their pain points and offer customized strategies that drive growth. Our expertise includes cloud computing, cybersecurity, and AI-powered solutions. We are committed to delivering sustainable, scalable solutions that add value and foster long-term success. Join our clients who are transforming their business through innovative technology.",
		phone: "254700987654",
		email: "info@techhubinnovations.com",
		category: "Technology",
		niche: "consulting",
		sponsored: false,
		isVerified: true,
		priceRange: "20000 - 100000",
		logo: "https://res.cloudinary.com/dqweh6zte/image/upload/v1668515292/starter/tcbh5s9bgx2pnby906nz.jpg",
		location: {
			coordinates: [-1.317681, 36.802796],
			city: "Nairobi",
			country: "Kenya",
		},
		socialMedia: [
			{
				name: "facebook",
				link: "https://www.facebook.com/techhubinnovations",
			},
			{
				name: "instagram",
				link: "https://www.instagram.com/techhubinnovations",
			},
			{
				name: "linkedin",
				link: "https://www.linkedin.com/company/techhubinnovations",
			},
			{ name: "twitter", link: "https://twitter.com/techhubinnovations" },
		],
		owner: "92a57d16ce0e75dfb18f67baa5",
		photos: [
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704752520/afrex/About/pexels-antony-trivet-14167593_mkakgh.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751922/afrex/About/two-african-businessman-meeting-together_siqvfe.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751125/afrex/homepage/person-office-during-work-day_xgnul0.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704749161/afrex/homepage/complex-aerial-view-city_qsayli.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704895216/afrex/news/blogimage1_zmgpta.png",
		],
	},
	{
		_id: "743f5293c8a7f592dbac4731",
		name: "QuickFix Electronics",
		description:
			"QuickFix Electronics is a trusted provider of electronic repair services. We offer quick and reliable repairs for all types of consumer electronics, including smartphones, laptops, and home appliances. Our skilled technicians use advanced tools to fix any issues and return your devices in perfect working condition. With competitive pricing and exceptional customer service, we ensure a hassle-free experience. Whether it's a cracked screen or software malfunction, we are here to provide fast solutions.",
		phone: "254711234567",
		email: "service@quickfixelectronics.com",
		category: "Services",
		niche: "electronics repair",
		sponsored: true,
		isVerified: true,
		priceRange: "500 - 10000",
		logo: "https://res.cloudinary.com/dqweh6zte/image/upload/v1668515292/starter/tcbh5s9bgx2pnby906nz.jpg",
		location: {
			coordinates: [-1.307263, 36.811398],
			city: "Nairobi",
			country: "Kenya",
		},
		socialMedia: [
			{
				name: "facebook",
				link: "https://www.facebook.com/quickfixelectronics",
			},
			{
				name: "instagram",
				link: "https://www.instagram.com/quickfixelectronics",
			},
			{
				name: "linkedin",
				link: "https://www.linkedin.com/company/quickfixelectronics",
			},
			{
				name: "twitter",
				link: "https://twitter.com/quickfixelectronics",
			},
		],
		owner: "33e91d16ce0e75dfb18f67baa5",
		photos: [
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704752520/afrex/About/pexels-antony-trivet-14167593_mkakgh.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751922/afrex/About/two-african-businessman-meeting-together_siqvfe.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751125/afrex/homepage/person-office-during-work-day_xgnul0.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704749161/afrex/homepage/complex-aerial-view-city_qsayli.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704895216/afrex/news/blogimage1_zmgpta.png",
		],
	},
	{
		_id: "743f5293c8a7f60cd6ac4731",
		name: "QuickFix Electronics",
		description:
			"QuickFix Electronics is a trusted provider of electronic repair services. We offer quick and reliable repairs for all types of consumer electronics, including smartphones, laptops, and home appliances. Our skilled technicians use advanced tools to fix any issues and return your devices in perfect working condition. With competitive pricing and exceptional customer service, we ensure a hassle-free experience. Whether it's a cracked screen or software malfunction, we are here to provide fast solutions.",
		phone: "254711234567",
		email: "service@quickfixelectronics.com",
		category: "Services",
		niche: "electronics repair",
		sponsored: true,
		isVerified: true,
		priceRange: "500 - 10000",
		logo: "https://res.cloudinary.com/dqweh6zte/image/upload/v1668515292/starter/tcbh5s9bgx2pnby906nz.jpg",
		location: {
			coordinates: [-1.307263, 36.811398],
			city: "Nairobi",
			country: "Kenya",
		},
		socialMedia: [
			{
				name: "facebook",
				link: "https://www.facebook.com/quickfixelectronics",
			},
			{
				name: "instagram",
				link: "https://www.instagram.com/quickfixelectronics",
			},
			{
				name: "linkedin",
				link: "https://www.linkedin.com/company/quickfixelectronics",
			},
			{
				name: "twitter",
				link: "https://twitter.com/quickfixelectronics",
			},
		],
		owner: "33e91d16ce0e75dfb18f67baa5",
		photos: [
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704752520/afrex/About/pexels-antony-trivet-14167593_mkakgh.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751922/afrex/About/two-african-businessman-meeting-together_siqvfe.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751125/afrex/homepage/person-office-during-work-day_xgnul0.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704749161/afrex/homepage/complex-aerial-view-city_qsayli.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704895216/afrex/news/blogimage1_zmgpta.png",
		],
	},
	{
		_id: "b29b63610ed67a3dbe93078d",
		name: "Sunshine Florists",
		description:
			"Sunshine Florists is a family-owned flower shop offering a wide variety of fresh flowers for every occasion. From weddings to birthdays, our bouquets and arrangements are handcrafted with care. We pride ourselves on our high-quality flowers and personalized service. Whether you're looking for a simple bouquet or a grand floral display, we have you covered. Visit us and experience the beauty of nature through our elegant floral designs.",
		phone: "254713456789",
		email: "flowers@sunshineflorists.com",
		category: "Retail",
		niche: "florist",
		sponsored: false,
		isVerified: true,
		priceRange: "200 - 5000",
		logo: "https://res.cloudinary.com/dqweh6zte/image/upload/v1668515292/starter/tcbh5s9bgx2pnby906nz.jpg",
		location: {
			coordinates: [-1.312854, 36.815079],
			city: "Nairobi",
			country: "Kenya",
		},
		socialMedia: [
			{
				name: "facebook",
				link: "https://www.facebook.com/sunshineflorists",
			},
			{
				name: "instagram",
				link: "https://www.instagram.com/sunshineflorists",
			},
			{
				name: "linkedin",
				link: "https://www.linkedin.com/company/sunshineflorists",
			},
			{ name: "twitter", link: "https://twitter.com/sunshineflorists" },
		],
		owner: "4b70d16ce0e75dfb18f67baa5",
		photos: [
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704752520/afrex/About/pexels-antony-trivet-14167593_mkakgh.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751922/afrex/About/two-african-businessman-meeting-together_siqvfe.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751125/afrex/homepage/person-office-during-work-day_xgnul0.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704749161/afrex/homepage/complex-aerial-view-city_qsayli.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704895216/afrex/news/blogimage1_zmgpta.png",
		],
	},
	{
		_id: "a29b7261c7467a3dbe93078d",
		name: "Sunshine Florists",
		description:
			"Sunshine Florists is a family-owned flower shop offering a wide variety of fresh flowers for every occasion. From weddings to birthdays, our bouquets and arrangements are handcrafted with care. We pride ourselves on our high-quality flowers and personalized service. Whether you're looking for a simple bouquet or a grand floral display, we have you covered. Visit us and experience the beauty of nature through our elegant floral designs.",
		phone: "254713456789",
		email: "flowers@sunshineflorists.com",
		category: "Retail",
		niche: "florist",
		sponsored: false,
		isVerified: true,
		priceRange: "200 - 5000",
		logo: "https://res.cloudinary.com/dqweh6zte/image/upload/v1668515292/starter/tcbh5s9bgx2pnby906nz.jpg",
		location: {
			coordinates: [-1.312854, 36.815079],
			city: "Nairobi",
			country: "Kenya",
		},
		socialMedia: [
			{
				name: "facebook",
				link: "https://www.facebook.com/sunshineflorists",
			},
			{
				name: "instagram",
				link: "https://www.instagram.com/sunshineflorists",
			},
			{
				name: "linkedin",
				link: "https://www.linkedin.com/company/sunshineflorists",
			},
			{ name: "twitter", link: "https://twitter.com/sunshineflorists" },
		],
		owner: "4b70d16ce0e75dfb18f67baa5",
		photos: [
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704752520/afrex/About/pexels-antony-trivet-14167593_mkakgh.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751922/afrex/About/two-african-businessman-meeting-together_siqvfe.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751125/afrex/homepage/person-office-during-work-day_xgnul0.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704749161/afrex/homepage/complex-aerial-view-city_qsayli.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704895216/afrex/news/blogimage1_zmgpta.png",
		],
	},
	{
		_id: "f93bd7b2c0e8f8dcb6717d52",
		name: "Precision Legal Advisors",
		description:
			"Precision Legal Advisors is a law firm providing expert legal services to businesses and individuals. Our team of experienced lawyers specializes in corporate law, intellectual property, and commercial disputes. We offer tailored legal solutions that are both practical and cost-effective. Whether you need assistance with contract negotiations, trademark registration, or litigation, our firm has the expertise to help. Trust us to handle your legal matters with integrity and professionalism.",
		phone: "254705432198",
		email: "contact@precisionlegal.com",
		category: "Legal",
		niche: "law firm",
		sponsored: false,
		isVerified: true,
		priceRange: "10000 - 50000",
		logo: "https://res.cloudinary.com/dqweh6zte/image/upload/v1668515292/starter/tcbh5s9bgx2pnby906nz.jpg",
		location: {
			coordinates: [-1.320476, 36.817366],
			city: "Nairobi",
			country: "Kenya",
		},
		socialMedia: [
			{
				name: "facebook",
				link: "https://www.facebook.com/precisionlegaladvisors",
			},
			{
				name: "instagram",
				link: "https://www.instagram.com/precisionlegaladvisors",
			},
			{
				name: "linkedin",
				link: "https://www.linkedin.com/company/precisionlegaladvisors",
			},
			{ name: "twitter", link: "https://twitter.com/precisionlegal" },
		],
		owner: "64d92d16ce0e75dfb18f67baa5",
		photos: [
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704752520/afrex/About/pexels-antony-trivet-14167593_mkakgh.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751922/afrex/About/two-african-businessman-meeting-together_siqvfe.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704751125/afrex/homepage/person-office-during-work-day_xgnul0.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704749161/afrex/homepage/complex-aerial-view-city_qsayli.jpg",
			"https://res.cloudinary.com/dqweh6zte/image/upload/v1704895216/afrex/news/blogimage1_zmgpta.png",
		],
	},
];
